apiVersion: build.pivotal.io/v1alpha1
kind: Image
metadata:
  name: petclinic-image
spec:
  tag: glenioborges/petclinic
  serviceAccount: kpack-service-account
  cacheSize: "1.5Gi"
  builder:
    name: default
    kind: ClusterBuilder
  source:
    git:
      url: https://github.com/dambor/spring-petclinic
      revision: 7387637a4d9d271ea6de0c884e8877e8b176d650
